go/src/github.com/damorimRG/frisk-back/DockerFiddle/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'share#index'
  get 'faq', to: 'share#faq', as: 'faq'
  get 'tutorial', to: 'share#tutorial', as: 'tutorial'
  get '404', to: 'share#not_found'
  get '/create', to: 'share#create', as: 'create_session'
  post 'share/:session', to: 'share#share'
  post '/killall', to: 'share#kill_containers'
  get ':session', to: 'share#shared', as: 'run_instance'
end

go/src/github.com/damorimRG/frisk-back/DockerFiddle/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

go/src/github.com/damorimRG/frisk-back/DockerFiddle/app/models/instance.rb
class Instance < ApplicationRecord
    belongs_to :session
end

go/src/github.com/damorimRG/frisk-back/DockerFiddle/app/models/session.rb
class Session < ApplicationRecord
    has_many :instances
end

go/src/github.com/damorimRG/frisk-back/DockerFiddle/app/models/visit.rb
class Visit < ApplicationRecord
end

go/src/github.com/damorimRG/frisk-back/DockerFiddle/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

go/src/github.com/damorimRG/frisk-back/DockerFiddle/app/controllers/share_controller.rb
require 'net/ssh'
require 'aws-sdk-s3'

class ShareController < ApplicationController

    skip_before_action :verify_authenticity_token
    #ENDPOINT = 'pg.localhost'
    ENDPOINT = 'pg.frisk.igorwiese.com'

    def index
        
    end

    def faq

    end

    def tutorial

    end

    def kill_containers
        pwd = PwdInterface.new ENDPOINT
        pwdSession = params[:sessionId]
        pwdInstance = params[:instance]
        delete = params[:delete]
        pwdInstances = pwd.get_instances(pwdSession)
        pwdInstances.each do |instance|
            if instance['name'] == pwdInstance
                Net::SSH.start("direct.#{ENDPOINT}", instance['proxy_host'], port: 8022) do |ssh|
                    command = 'stop'
                    command = 'rm -f' if delete
                    ssh.exec!("/usr/local/bin/docker #{command} \$(/usr/local/bin/docker ps -a -q)")
                    ssh.loop
                    render :json => {status: 'ok'}
                end
            end
        end
    end

    def not_found
        render :json => {status: 'not found', error: 404}
    end

    def create
        pwd = PwdInterface.new ENDPOINT
        pwdSession = pwd.create_session
        redirect_to "http://#{ENDPOINT}/p/#{pwdSession}"
    end

    def shared
        s3 = Aws::S3::Resource.new(region: 'us-east-1', 
                           access_key_id: 'AKIAJOVXNQ5CZTWEAZZA', 
                           secret_access_key: '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')

        session = Session.includes(:instances).find_by_uuid(params[:session])
        if not session
            return not_found
        end
        pwd = PwdInterface.new ENDPOINT
        pwdSession = pwd.create_session
        
        session.instances.each do |instance|
            pwdInstance = pwd.create_instance(pwdSession)

            downloadLink = s3.bucket('dockerfiddle').object("shares/#{session.uuid}/#{instance.uuid}.tar.gz").presigned_url(:get, expires_in: 60 * 60)
            Net::SSH.start("direct.#{ENDPOINT}", pwdInstance.proxy_host, port: 8022) do |ssh|
                ssh.exec!("cd / && curl \"#{downloadLink}\" -o root.tar.gz && tar xvf root.tar.gz -C /root && rm -rf root.tar.gz && mv /root/root/* /root && rm -rf /root/root")
                ssh.loop
            end
        end
        Visit.create(url: params[:session], session: pwdSession)
        redirect_to "http://#{ENDPOINT}/p/#{pwdSession}"
    end

    def share
        pwd = PwdInterface.new ENDPOINT
        pwdSession = params[:session]
        pwdInstances = pwd.get_instances(pwdSession)

        s3 = Aws::S3::Resource.new(region: 'us-east-1', 
                           access_key_id: 'AKIAJOVXNQ5CZTWEAZZA', 
                           secret_access_key: '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')

        session = Session.create(uuid: SecureRandom.uuid)
        pwdInstances.each do |pwdInstance|

            instance = Instance.create(uuid: SecureRandom.uuid, session_id: session.id)
            Net::SSH.start("direct.#{ENDPOINT}", pwdInstance['proxy_host'], port: 8022) do |ssh|
                
                ssh.exec! 'cd / && tar cvfz /root.tar.gz root/ --exclude ".*"'
                ssh.loop
                url = s3.bucket('dockerfiddle').object("shares/#{session.uuid}/#{instance.uuid}.tar.gz").presigned_url(:put)
                ssh.exec! "cd / && curl -X PUT \"#{url}\" -T /root.tar.gz && rm -rf /root.tar.gz"
                ssh.loop
            end
        end
        render json: {status: 'ok', uuid: session.uuid}
    end

end

go/src/github.com/damorimRG/frisk-back/DockerFiddle/app/helpers/application_helper.rb
module ApplicationHelper
    def project_name
        "Frisk"
    end
end

go/src/github.com/damorimRG/frisk-back/DockerFiddle/app/helpers/share_helper.rb
module ShareHelper
end

go/src/github.com/damorimRG/frisk-back/DockerFiddle/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link rel="icon" 
    type="image/png" 
    href="logo.png">
    <title><%= project_name %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-102886917-3"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-102886917-3');
    </script>

  </head>

  <body>
    <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-primary">
      <a class="navbar-brand" href="<%= root_path %>"><img src="/logo.png" width="32px"/></a>
      <a class="navbar-brand" href="<%= root_path %>"><%= project_name %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="<%= root_path %>">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= faq_path %>">Faq</a>
            </li><li class="nav-item">
            <a class="nav-link" href="<%= tutorial_path %>">Tutorial</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
    
      <div class="header clearfix">
          
      </div>
      <br />
      <br />
      <br />
      <br />
      <%= yield %>
    </div>
  </body>
</html>

go/src/github.com/damorimRG/frisk-back/DockerFiddle/app/views/share/faq.html.erb
<div class="row">
    <div class="col-lg-12">
        <h2>Frequently Asked Questions</h2>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <p>explain how we obtained these templates</p>
        <p>explain how it works</p>
        <p>explain that we use alpine linux and not debian-based linux</p>
        <p>explain that that we do not persist images and VM changes. we only store the files inside /root</p>
    </div>
</div>

go/src/github.com/damorimRG/frisk-back/DockerFiddle/app/views/share/index.html.erb
<div class="jumbotron" align="center">
  <h1 class="display-3"><%= project_name %>!</h1>
  <p class="lead">Prototyping your server-side project made easy</p>
  <hr class="my-4">
  <p><%= project_name %> is a tool for prototyping and sharing server-side projects compatible with Docker technology! <%= project_name %> is an on-going project. Hence, there might be interesting features that have not yet been implemented, or even unexpected behavior.</p>
</div>

<div class="row">
    <div class="col-lg-11">
        <h2>Frameworks</h2>
        <div class="form-group">
            <input class="form-control form-control-lg" type="text" placeholder="Filter..." id="filtertxt">
        </div>
    </div>
</div>

<div class="col-lg-12">
    <div class="row">
        <a href="/create">
            <div class="card text-white bg-secondary mb-3" style="max-width: 20rem;">
                <div class="card-body">
                    <h4 class="card-title">Empty</h4>
                    <ul>
                        <li>Language: N/A</li>
                        <li>Database: None</li>
                        <li>Template Engine: None </li>
                    </ul>
                </div>
            </div>
        </a>
        <a href="/ef670248-3470-40cd-ab9d-747c699ba8e5">
            <div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
                <div class="card-body">
                    <h4 class="card-title">Express.js</h4>
                    <ul>
                        <li>Node.js: 6.9.5</li>
                        <li>Database: None</li>
                        <li>Template Engine: None </li>
                    </ul>
                </div>
            </div>
        </a>
        <a href="/baa51d11-bd4d-413d-bf79-c201171026f1">
            <div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
                <div class="card-body">
                    <h4 class="card-title">Express.js</h4>
                    <ul>
                        <li>Node.js: 6.9.5</li>
                        <li>Database: None</li>
                        <li>Template Engine: Jade </li>
                    </ul>
                </div>
            </div>
        </a>
        <a href="/a402d251-7f7b-411e-bbd5-92a8b6f39650">
            <div class="card text-white bg-info mb-3" style="max-width: 20rem;">
                <div class="card-body">
                    <h4 class="card-title">Rails 5</h4>
                    <ul>
                        <li>Ruby: 2.5.3</li>
                        <li>Database: SQLite 3</li>
                        <li>Template Engine:  ERB </li>
                    </ul>
                </div>
            </div>
        </a>
        <a href="/294ac2bb-bea5-4df7-9822-0b39cade2d04">
            <div class="card text-white bg-info mb-3" style="max-width: 20rem;">
                <div class="card-body">
                    <h4 class="card-title">Rails 5</h4>
                    <ul>
                        <li>Ruby: 2.5.3</li>
                        <li>Database: None</li>
                        <li>Template Engine:  ERB</li>
                    </ul>
                </div>
            </div>
        </a>
        <a href="/38281a4f-effa-4e6a-8ed7-b1b5fbea6972">
            <div class="card text-white bg-success mb-3" style="max-width: 20rem;">
                <div class="card-body">
                    <h4 class="card-title">Django</h4>
                    <ul>
                        <li>Python: 3</li>
                        <li>Database: Postgres</li>
                        <li>Template Engine: None</li>
                    </ul>
                </div>
            </div>
        </a>
        <a href="/4c33d028-4ead-422e-9cbc-49ecdf8edb0e">
            <div class="card text-white bg-secondary mb-3" style="max-width: 20rem;">
                <div class="card-body">
                    <h4 class="card-title">Flask</h4>
                    <ul>
                        <li>Python: 3</li>
                        <li>Database: None</li>
                        <li>Template Engine: None</li>
                    </ul>
                </div>
            </div>
        </a>
        <a href="/b132dae2-8e31-4df6-8137-276a0614dba1">
            <div class="card text-white bg-secondary mb-3" style="max-width: 20rem;">
                <div class="card-body">
                    <h4 class="card-title">Flask</h4>
                    <ul>
                        <li>Python: 3</li>
                        <li>Database: SQlite 3</li>
                        <li>Template Engine: Native</li>
                    </ul>
                </div>
            </div>
        </a>
        <a href="/3f2069a7-c42e-4947-a9e7-491ad6e0418b">
            <div class="card text-white bg-secondary mb-3" style="max-width: 20rem;">
                <div class="card-body">
                    <h4 class="card-title">Flask</h4>
                    <ul>
                        <li>Python: 3</li>
                        <li>Database: None</li>
                        <li>Template Engine: Native</li>
                    </ul>
                </div>
            </div>
        </a>
    </div>
</div>